---
AllCops: 
  TargetRubyVersion: 3.4
  NewCops: enable

plugins: 
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-sequel

Metrics/BlockLength: 
  Enabled: true
  Exclude: 
    - spec/**/* # Minitest's nested test structure requires large blocks
    - app/controllers/**/*.rb # Roda's nested controllers require large blocks
    - rakefile # Rake namespaces produce large blocks

Security/YAMLLoad:
  Enabled: true
  Exclude: 
    - spec/**/* 