---
development:
  DATABASE_URL: sqlite://db/local/development.db
  DB_KEY: +ltJ7lJp4ozd36eb3+QWw5ulh07VcLvLMTP3ZgNAbUE=
test:
  DATABASE_URL: sqlite://db/local/test.db 
  DB_KEY: m9lQKLdqsoD+DOjaIfqdGxFv+nOq/n7nBoqusmJfqIg=
