# COPY this file to secrets.yml and modify as needed
---
development:
  DATABASE_URL: sqlite://db/local/dev.db
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_dev_key_here
  SECURE_SCHEME: HTTP
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  UPLOAD_PATH: uploads/dev
  
test:
  DATABASE_URL: sqlite://db/local/test.db
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_test_key_here
  SECURE_SCHEME: HTTP
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  UPLOAD_PATH: uploads/test

production:
  DATABASE_URL: <assigned by production service>
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_production_key_here
  SECURE_SCHEME: HTTPS
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  UPLOAD_PATH: path_where_you_want_to_store_files