# COPY this file to secrets.yml and modify as needed
---
development:
  DATABASE_URL: sqlite://db/local/dev.db
  DB_KEY: your_dev_key_here
  
test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: your_test_key_here

production:
  DATABASE_URL: <assigned by production service>