# COPY this file to secrets.yml and modify as needed
---
development:
  DATABASE_URL: sqlite://db/local/dev.db
  DB_KEY: your_dev_key_here
  SECURE_SCHEME: HTTP
  REDISCLOUD_URL: redis://default
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: sharon.lin@iss.nthu.edu.tw

  
test:
  DATABASE_URL: sqlite://db/local/test.db
  DB_KEY: your_test_key_here
  SECURE_SCHEME: HTTP

production:
  DATABASE_URL: <assigned by production service>
  SECURE_SCHEME: HTTPS