# COPY this file to secrets.yml and modify as needed
---
development:
  DATABASE_URL: sqlite://db/local/dev.db
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_dev_key_here
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SECURE_SCHEME: HTTP
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  AWS_ACCESS_KEY_ID: your_key_id
  AWS_SECRET_ACCESS_KEY: your_secret_key
  AWS_REGION: ap-northeast-1
  AWS_BUCKET: uccme
  AWS_PREFIX: dev
  
test:
  DATABASE_URL: sqlite://db/local/test.db
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_test_key_here
  SIGNING_KEY: nNuYJVHnMTPfArqFo3Rb81xvXoPDuqcdoUhjWVfGooE=
  VERIFY_KEY: j50XXfk5tXJ9oWomovLVOFlbgKKY/YSDPHAy4s1fA6U=
  SECURE_SCHEME: HTTP
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  AWS_ACCESS_KEY_ID: your_key_id
  AWS_SECRET_ACCESS_KEY: your_secret_key
  AWS_REGION: ap-northeast-1
  AWS_BUCKET: uccme
  AWS_PREFIX: test

production:
  DATABASE_URL: <assigned by production service>
  MSG_KEY: <`rake new_key:msg`>
  DB_KEY: your_production_key_here
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  SECURE_SCHEME: HTTPS
  MJ_APIKEY_PUBLIC: MAILJET API KEY
  MJ_APIKEY_PRIVATE: MAILJET SECRET KEY
  SENDER_EMAIL: your_email_address
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  AWS_ACCESS_KEY_ID: your_key_id
  AWS_SECRET_ACCESS_KEY: your_secret_key
  AWS_REGION: ap-northeast-1
  AWS_BUCKET: uccme
  AWS_PREFIX: prod